Client/b2b_client/b2b_client/urls.py
from django.conf.urls import url, include
from b2b_control.views import *

urlpatterns = [
    url(r'', include('b2b_control.urls')),
]

Client/b2b_client/b2b_control/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from b2b_control.decorators import auth_required
from b2b_control import views

app_name = 'b2b_control'

urlpatterns = [
       url(r'^$', TemplateView.as_view(template_name='index.html'), name='index'),
       url(r'^accounts/login/$', views.login, name='login'),
       url(r'^accounts/logout/$', views.logout, name='logout'),
       url(r'^control/$', views.control, name='control'),
       url(r'^command/$', views.command, name='command'),
       url(r'^image/[0-9]*$', views.image, name='image'),
]

Client/b2b_client/b2b_control/models.py
from django.db import models


class Message(models.Model):
    message = models.CharField(max_length=100)


class Command(models.Model):
    # character send
    characters = models.CharField(max_length=100, default='')
    # the force of the character (manage the speed)
    value = models.IntegerField(default=1)

Client/b2b_client/b2b_control/forms/login_form.py
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField(label='Your name')
    password = forms.CharField(label='Your password', widget=forms.PasswordInput())

Client/b2b_client/b2b_control/views.py
from b2b_control.forms import LoginForm
from component.services.api import login as api_login
from component.services.api import get_image as api_get_image
from component.services.api import post_command as api_post_command
from b2b_control.decorators import auth_required
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse


def login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            response = api_login(form.cleaned_data)
            if response.ok:
                user = response.json()
                request.session['user'] = user
                request.session['is_authenticated'] = True

                return HttpResponseRedirect(reverse('b2b_control:control'))

            return render(request, 'registration/login.html',
                          {'form': form, 'errors': response.json()['errors']['non_field_errors']})
    else:
        form = LoginForm()

    return render(request, 'registration/login.html', {'form': form})


def logout(request):
    try:
        del request.session['is_authenticated']
        del request.session['user']
    except KeyError:
        pass
    return HttpResponseRedirect(reverse('b2b_control:index'))


@auth_required
def control(request):
    return render(request, 'control/control.html')


@auth_required
def command(request):
    response = api_post_command(request.POST, request.session['user']['token'])

    if response.ok:
        return HttpResponse(response)

    return render(request, 'registration/login.html')


@auth_required
def image(request):

    response = api_get_image(request.session['user']['token'])
    if response.ok:
        return HttpResponse(response, content_type="image/jpeg")
    return render(request, 'registration/login.html')

Client/b2b_client/b2b_control/templates/base.html
{% load staticfiles %}
<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang=""> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>B2B Control - {% block title %}{% endblock %}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="apple-touch-icon" href="{% static "apple-touch-icon.png" %}">

        <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
        <style>
            body {
                padding-top: 50px;
                padding-bottom: 20px;
            }
        </style>
        <link rel="stylesheet" href="{% static "css/bootstrap-theme.min.css" %}">
        <link rel="stylesheet" href="{% static "css/main.css" %}">
        <script src="{% static "js/vendor/modernizr-2.8.3-respond-1.4.2.min.js" %}"></script>
    </head>
    <body>

    <div class="container">
        <div>
            {% block heading %}{% endblock %}
        </div>
        <div class="row">
            {% block content %}{% endblock %}
        </div>

      <hr>

    <footer>
        {% block footer %}{% endblock %}
        <p>&copy; B2B - 2017</p>
    </footer>
    </div> <!-- /container -->        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="{% static "js/vendor/jquery-1.11.2.min.js" %}"><\/script>')</script>
        <script src="{% static "js/jquery-3.1.1.min.js" %}"></script>
        <script src="{% static "js/vendor/bootstrap.min.js" %}"></script>

        <script src="{% static "js/main.js" %}"></script>
        <script>
            window.command_url = '{{ COMMAND_URL }}';
            window.image_url = '{{ IMAGE_URL }}';
        </script>
        <script src="{% static 'js/b2b_control/control.js' %}"></script>


    </body>
</html>

Client/b2b_client/b2b_control/templates/control/control.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="soundfile" data-src="{% static "sound/screenshot.mp3" %}"></div>

    <div class="col-md-4">
        <div class="row stream">
            <img class="img-stream scop" src="{% static "img/scop.png" %}"/>
            <img class="img-stream cam" src=""/>
        </div>
        <div class="row">
            <label for="camera">Webcam</label><input id="camera" class="camera" type="checkbox">
            <button id="capture" class="capture" value="screenshot">Capture</button>
        </div>
    </div>

    <div class="col-md-4">
        <div class="row command">
            <button class='col-md-4 direction' value="a"><img class="img-responsive" src="{% static "img/arrow-35.png" %}"/></button>
            <button class='col-md-4 direction forward' value="o"><img class="img-responsive" src="{% static "img/34-202.png" %}"/></button>
            <button class='col-md-4 direction' value="e"><img class="img-responsive" src="{% static "img/arrow-34.png" %}"/></button>
        </div>
        <div class="row command">
            <button class='col-md-4 direction' value="k"><img class="img-responsive" src="{% static "img/34-203.png" %}"/></button>
            <button class='col-md-4 direction' value="l"><img class="img-responsive" src="{% static "img/34-201.png" %}"/></button>
            <button class='col-md-4 direction' value="m"><img class="img-responsive" src="{% static "img/34-200.png" %}"/></button>

        </div>

        <div class="row command row-stop">
            <button class='col-md-12 direction direction-stop' value="STOP"><img class="img-responsive img-stop" src="{% static "img/stop.png" %}"/></button>
        </div>
        <div class="row">
            <label for="speed"> Vitesse </label>
            <select class="speed">
                <option value="1">1</option>
                <option value="2">2</option>
            </select>
        </div>
    </div>

    <div class="col-md-4">
        <div class="row log">
            <textarea class='log-zone'></textarea>
        <div class="row">
        </div>
            <a class='clear-log' href="#">Clear log</a>
        </div>
    </div>

    <div class="col-md-6">
        <div class="row">
            <img class="capture-img" src=""/>
        </div>
    </div>

{% endblock %}

{% block footer %}
     <p><a href="{% url 'b2b_control:logout' %}">Déconnexion</a></p>
{% endblock %}

Client/b2b_client/b2b_control/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Login{% endblock %}

{% block toggle_login %}{% endblock %}

{% block content %}
   <a href="{% url 'b2b_control:login' %}">Se connecter</a>
{% endblock %}